"""
Interactive script to help set up API keys for real data
"""
import os
from pathlib import Path

def setup_api_keys():
    """Interactive API key setup"""
    print("=" * 60)
    print("Gaming Data Pipeline - API Key Setup")
    print("=" * 60)
    print("\nThis script will help you set up API keys for real gaming data.")
    print("All APIs are FREE to use (with rate limits).\n")
    
    env_file = Path(".env")
    env_content = {}
    
    # Read existing .env if it exists
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_content[key.strip()] = value.strip()
    
    print("API Key Setup Guide:\n")
    
    # OpenDota (No key needed)
    print("1. OpenDota API (Dota 2)")
    print("   [OK] No API key required!")
    print("   URL: https://www.opendota.com/")
    print("   Rate limit: 60 requests/minute\n")
    
    # Steam API
    print("2. Steam Web API")
    print("   Get your free API key:")
    print("   URL: https://steamcommunity.com/dev/apikey")
    print("   Steps:")
    print("      - Log in with your Steam account")
    print("      - Enter a domain name (can be 'localhost')")
    print("      - Click 'Register'")
    print("      - Copy your API key\n")
    
    steam_key = input("   Enter your Steam API key (or press Enter to skip): ").strip()
    if steam_key:
        env_content["STEAM_API_KEY"] = steam_key
        print("   [OK] Steam API key saved!\n")
    else:
        print("   [SKIP] Skipped Steam API key (will use mock data)\n")
    
    # Riot Games API
    print("3. Riot Games API (Valorant)")
    print("   Get your free API key:")
    print("   URL: https://developer.riotgames.com/")
    print("   Steps:")
    print("      - Create a Riot Games developer account")
    print("      - Go to 'API Keys' section")
    print("      - Generate a new API key")
    print("      - Copy your API key")
    print("   Note: Riot API keys expire after 24 hours (free tier)\n")
    
    riot_key = input("   Enter your Riot API key (or press Enter to skip): ").strip()
    if riot_key:
        env_content["RIOT_API_KEY"] = riot_key
        print("   [OK] Riot API key saved!\n")
    else:
        print("   [SKIP] Skipped Riot API key (will use mock data)\n")
    
    # Mock data setting
    print("4. Mock Data")
    use_mock = input("   Use mock data when APIs are unavailable? (y/n, default: y): ").strip().lower()
    env_content["MOCK_DATA_ENABLED"] = "true" if use_mock != "n" else "false"
    
    # Database setting
    print("\n5. Database")
    use_duckdb = input("   Use DuckDB (embedded, no setup)? (y/n, default: y): ").strip().lower()
    env_content["USE_DUCKDB"] = "true" if use_duckdb != "n" else "true"
    
    # Write .env file
    print("\n" + "=" * 60)
    print("Saving configuration to .env file...")
    
    with open(env_file, 'w', encoding='utf-8') as f:
        f.write("# Gaming Data Pipeline Configuration\n")
        f.write("# Generated by setup_api_keys.py\n")
        f.write("# DO NOT COMMIT THIS FILE TO VERSION CONTROL!\n")
        f.write("# This file contains sensitive API keys and is in .gitignore\n\n")
        
        # Database
        f.write("# Database Configuration\n")
        f.write(f"USE_DUCKDB={env_content.get('USE_DUCKDB', 'true')}\n")
        f.write("DUCKDB_PATH=data/gaming_pipeline.duckdb\n\n")
        
        # Steam API
        f.write("# Steam API\n")
        if env_content.get("STEAM_API_KEY"):
            f.write(f"STEAM_API_KEY={env_content['STEAM_API_KEY']}\n")
        else:
            f.write("STEAM_API_KEY=\n")
        f.write("STEAM_API_BASE_URL=https://api.steampowered.com\n\n")
        
        # OpenDota API
        f.write("# OpenDota API (No key required)\n")
        f.write("OPENDOTA_API_BASE_URL=https://api.opendota.com/api\n\n")
        
        # Riot API
        f.write("# Riot Games API\n")
        if env_content.get("RIOT_API_KEY"):
            f.write(f"RIOT_API_KEY={env_content['RIOT_API_KEY']}\n")
        else:
            f.write("RIOT_API_KEY=\n")
        f.write("RIOT_API_BASE_URL=https://americas.api.riotgames.com\n\n")
        
        # Pipeline settings
        f.write("# Pipeline Configuration\n")
        f.write("POLL_INTERVAL_MINUTES=15\n")
        f.write("BATCH_SIZE=1000\n")
        f.write("MAX_RETRIES=3\n")
        f.write("RETRY_DELAY_SECONDS=60\n")
        f.write(f"MOCK_DATA_ENABLED={env_content.get('MOCK_DATA_ENABLED', 'true')}\n\n")
        
        # Logging
        f.write("# Logging\n")
        f.write("LOG_LEVEL=INFO\n")
        f.write("LOG_FILE_PATH=logs/pipeline.log\n\n")
        
        # ML
        f.write("# ML Configuration\n")
        f.write("FORECAST_HORIZON_DAYS=7\n")
        f.write("MODEL_RETRAIN_INTERVAL_DAYS=7\n\n")
        
        # Environment
        f.write("# Environment\n")
        f.write("ENVIRONMENT=development\n")
    
    print("[OK] Configuration saved to .env file!")
    print("\n" + "=" * 60)
    print("Setup Complete!")
    print("=" * 60)
    print("\nNext steps:")
    print("1. Run ETL pipeline: python src/etl/run_pipeline.py")
    print("2. Generate forecasts: python src/ml/generate_forecasts.py")
    print("3. Launch dashboard: python -m streamlit run dashboard/app.py")
    print("\nTip: OpenDota API works without a key and provides real Dota 2 data!")

if __name__ == "__main__":
    setup_api_keys()
